from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

# validation/
VALIDATION_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = VALIDATION_DIR / "data"

# Allow this test file to import validation/gcode_validator.py.
sys.path.insert(0, str(VALIDATION_DIR))

from gcode_validator import find_bgcode_converter, validate_upload

REAL_GCODE = DATA_DIR / "Rook1_0.4n_0.15mm_PLA_COREONE_1h5m.gcode"
REAL_BGCODE = DATA_DIR / "Rook1_0.4n_0.15mm_PLA_COREONE_1h5m.bgcode"


def make_coreone_gcode(
    *,
    metadata_model: str = "COREONE",
    m862_model: str = "COREONE",
    temperature: int = 230,
    include_config_end: bool = True,
    include_nozzle_off: bool = True,
    include_filament_type: bool = True,
    extra_metadata: str = "",
) -> str:
    """Create a small CORE One G-code fixture for unit tests."""

    filament_type = "; filament_type = PLA\n" if include_filament_type else ""
    nozzle_off = "M104 S0\n" if include_nozzle_off else ""
    config_end = "; prusaslicer_config = end\n" if include_config_end else ""

    return f"""; generated by PrusaSlicer test fixture

M862.1 P0.4 A0 F1
M862.3 P "{m862_model}"
M862.5 P2
M862.6 P"Input shaper"
G28
G1 X10 Y10 Z0.2 F3000

{nozzle_off}M140 S0
M107
M84 X Y E

; prusaslicer_config = begin
; printer_model = {metadata_model}
; printer_variant = HF0.4
; printer_settings_id = Prusa CORE One HF0.4 nozzle
; printer_technology = FFF
; print_settings_id = 0.15mm SPEED @COREONE HF0.4
; nozzle_diameter = 0.4
; nozzle_high_flow = 1
{filament_type}; filament_abrasive = 0
; filament_colour = #FF8000
; filament_settings_id = Prusament PLA @COREONE HF0.4
; bed_shape = 0x0,250x0,250x220,0x220
; max_print_height = 270
; max_layer_z = 20
; temperature = {temperature}
; bed_temperature = 60
; first_layer_temperature = {temperature}
; first_layer_bed_temperature = 60
; layer_height = 0.15
; filament used [g] = 12.8
; estimated printing time (normal mode) = 1h 5m
{extra_metadata}{config_end}"""


def print_match_result(result: dict) -> None:
    """Print the matched printer information for successful tests."""

    print()
    print("    Validation result")
    print(f"    Status          : {result['status']}")
    print(f"    Matched printer : {result['compatible_printer']}")
    print(f"    Profile         : {result['compatible_profile']}")
    print(f"    Material        : {result['required_material']}")
    print(f"    Next step       : {result['next_step']}")


class TestGCodeValidator(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name)

    def tearDown(self) -> None:
        self.temp_dir.cleanup()

    def write_file(self, name: str, content: str) -> Path:
        path = self.root / name
        path.write_text(content, encoding="utf-8")
        return path

    # ------------------------------------------------------------------
    # Synthetic unit tests
    # ------------------------------------------------------------------
    def test_valid_coreone_gcode_matches_core_one(self) -> None:
        path = self.write_file(
            "valid_coreone.gcode",
            make_coreone_gcode(),
        )

        result = validate_upload(path)

        self.assertTrue(result["passed"])
        self.assertEqual(result["status"], "PASS")
        self.assertEqual(result["compatible_profile"], "core_one_hf04")
        self.assertEqual(
            result["compatible_printer"],
            "Prusa CORE One HF0.4 nozzle",
        )
        self.assertEqual(result["required_material"], "PLA")
        self.assertEqual(result["next_step"], "SELECT_PRINTER")

        print_match_result(result)

    def test_missing_file_fails_stage_1(self) -> None:
        result = validate_upload(self.root / "missing.gcode")

        self.assertFalse(result["passed"])
        self.assertEqual(result["failed_stage"], 1)
        self.assertEqual(result["next_step"], "UPLOAD_GCODE")

    def test_unsupported_extension_fails_stage_1(self) -> None:
        path = self.write_file(
            "fake.txt",
            make_coreone_gcode(),
        )

        result = validate_upload(path)

        self.assertFalse(result["passed"])
        self.assertEqual(result["failed_stage"], 1)

    def test_incomplete_prusaslicer_config_fails_stage_2(self) -> None:
        path = self.write_file(
            "incomplete_config.gcode",
            make_coreone_gcode(include_config_end=False),
        )

        result = validate_upload(path)

        self.assertFalse(result["passed"])
        self.assertEqual(result["failed_stage"], 2)

    def test_missing_nozzle_shutdown_fails_stage_2(self) -> None:
        path = self.write_file(
            "unsafe_end.gcode",
            make_coreone_gcode(include_nozzle_off=False),
        )

        result = validate_upload(path)

        self.assertFalse(result["passed"])
        self.assertEqual(result["failed_stage"], 2)
        self.assertIn("M104 S0", result["errors"][0])

    def test_missing_required_metadata_fails_stage_3(self) -> None:
        path = self.write_file(
            "missing_material.gcode",
            make_coreone_gcode(include_filament_type=False),
        )

        result = validate_upload(path)

        self.assertFalse(result["passed"])
        self.assertEqual(result["failed_stage"], 3)
        self.assertIn("filament_type", result["errors"][0])

    def test_conflicting_metadata_fails_stage_3(self) -> None:
        path = self.write_file(
            "conflicting_metadata.gcode",
            make_coreone_gcode(
                extra_metadata="; printer_model = MK4\n",
            ),
        )

        result = validate_upload(path)

        self.assertFalse(result["passed"])
        self.assertEqual(result["failed_stage"], 3)
        self.assertIn(
            "Conflicting critical metadata",
            result["errors"][0],
        )

    def test_m862_model_mismatch_fails_stage_4(self) -> None:
        path = self.write_file(
            "m862_mismatch.gcode",
            make_coreone_gcode(m862_model="XL5IS"),
        )

        result = validate_upload(path)

        self.assertFalse(result["passed"])
        self.assertEqual(result["failed_stage"], 4)
        self.assertIn("M862.3", result["errors"][0])

    def test_unsupported_printer_profile_fails_stage_6(self) -> None:
        path = self.write_file(
            "unsupported_printer.gcode",
            make_coreone_gcode(
                metadata_model="MK4",
                m862_model="MK4",
            ),
        )

        result = validate_upload(path)

        self.assertFalse(result["passed"])
        self.assertEqual(result["failed_stage"], 6)
        self.assertEqual(result["compatible_profiles"], [])

    def test_temperature_over_limit_fails_stage_6(self) -> None:
        path = self.write_file(
            "too_hot.gcode",
            make_coreone_gcode(temperature=350),
        )

        result = validate_upload(path)

        self.assertFalse(result["passed"])
        self.assertEqual(result["failed_stage"], 6)

        reasons = " ".join(
            reason
            for check in result["printer_checks"].values()
            for reason in check["reasons"]
        )

        self.assertIn(
            "exceeds configured printer maximum",
            reasons,
        )

    # ------------------------------------------------------------------
    # Real sample files in validation/data/
    # ------------------------------------------------------------------
    def test_real_coreone_gcode_matches_core_one(self) -> None:
        self.assertTrue(
            REAL_GCODE.is_file(),
            f"Missing test file: {REAL_GCODE}",
        )

        result = validate_upload(REAL_GCODE)

        self.assertTrue(result["passed"], result)
        self.assertEqual(
            result["compatible_profile"],
            "core_one_hf04",
        )
        self.assertEqual(
            result["compatible_printer"],
            "Prusa CORE One HF0.4 nozzle",
        )
        self.assertEqual(
            result["required_material"],
            "PLA",
        )
        self.assertEqual(
            result["next_step"],
            "SELECT_PRINTER",
        )

        print_match_result(result)

    def test_real_missing_material_fails_stage_3(self) -> None:
        result = validate_upload(DATA_DIR / "broken_no_material.gcode")

        self.assertFalse(result["passed"], result)
        self.assertEqual(result["failed_stage"], 3, result)
        self.assertIn("filament_type", result["errors"][0])

    def test_real_wrong_printer_fails_stage_4(self) -> None:
        result = validate_upload(DATA_DIR / "broken_wrong_printer.gcode")

        self.assertFalse(result["passed"], result)
        self.assertEqual(result["failed_stage"], 4, result)
        self.assertIn("M862.3", result["errors"][0])

    def test_real_coreone_bgcode_matches_core_one(self) -> None:
        self.assertIsNotNone(
            find_bgcode_converter(),
            "Prusa libbgcode is required. Run bash backend/app/validation/setup_bgcode.sh "
            "or set BGCODE_BIN; see backend/app/validation/README.md.",
        )
        self.assertTrue(
            REAL_BGCODE.is_file(),
            f"Missing test file: {REAL_BGCODE}",
        )

        result = validate_upload(REAL_BGCODE)

        self.assertTrue(result["passed"], result)
        self.assertEqual(
            result["compatible_profile"],
            "core_one_hf04",
        )
        self.assertEqual(
            result["compatible_printer"],
            "Prusa CORE One HF0.4 nozzle",
        )
        self.assertEqual(
            result["required_material"],
            "PLA",
        )
        self.assertEqual(
            result["next_step"],
            "SELECT_PRINTER",
        )

        print_match_result(result)

    def test_real_bgcode_requires_converter(self) -> None:
        with patch("gcode_validator.find_bgcode_converter", return_value=None):
            result = validate_upload(REAL_BGCODE)

        self.assertFalse(result["passed"], result)
        self.assertEqual(result["failed_stage"], 2, result)
        self.assertIn("setup_bgcode.sh", result["errors"][0])

    def test_invalid_explicit_converter_does_not_fall_back(self) -> None:
        with patch.dict("os.environ", {"BGCODE_BIN": str(self.root / "missing.exe")}):
            self.assertIsNone(find_bgcode_converter())

    def test_corrupted_real_bgcode_fails_crc_check(self) -> None:
        data = bytearray(REAL_BGCODE.read_bytes())
        data[-1] ^= 1  # Corrupt the last block's stored checksum.
        path = self.root / "corrupted.bgcode"
        path.write_bytes(data)

        result = validate_upload(path)

        self.assertFalse(result["passed"], result)
        self.assertEqual(result["failed_stage"], 2, result)
        self.assertIn("CRC32", result["errors"][0])


if __name__ == "__main__":
    unittest.main(verbosity=2)
