"""HTTP tests for G-code upload (Fake Auth + temp storage root)."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import patch
from uuid import UUID

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.adapters.auth.fake import FakeAuthAdapter
from app.core.config import settings
from app.models.enums import JobStatus, UserRole
from app.models.print_job import PrintJob
from app.models.user import User

STUDENT_EMAIL = "22705555@student.uwa.edu.au"
STUDENT_PASSWORD = "secure-password-1"
FARMER_EMAIL = "farmer@uwa.edu.au"
FARMER_PASSWORD = "farmer-password-1"
ADMIN_EMAIL = "christopher.lamb@uwa.edu.au"
ADMIN_PASSWORD = "admin-password-1"

SAMPLE_GCODE = b"; generated by PrusaSlicer\nG28 ; home\n"


def _assert_no_jobs(db_session: Session) -> None:
    assert list(db_session.scalars(select(PrintJob))) == []


def _assert_no_files(storage_root: Path) -> None:
    remaining = [p for p in storage_root.rglob("*") if p.is_file()]
    assert remaining == []


def _assert_safe_error_payload(response, *, storage_root: Path) -> None:
    """Failure responses must stay structured and must not leak host paths."""
    body = response.text
    assert str(storage_root) not in body
    assert str(storage_root.resolve()) not in body
    detail = response.json()["detail"]
    assert isinstance(detail, dict)
    assert "code" in detail and "message" in detail
    message = detail["message"]
    assert isinstance(message, str)
    assert str(storage_root) not in message
    assert "/Users/" not in message
    assert "Traceback" not in body
    assert "OSError" not in body
    assert "RuntimeError" not in body
    assert "Permission denied" not in body


def _seed_profile(
    *,
    db_session: Session,
    auth_adapter: FakeAuthAdapter,
    email: str,
    password: str,
    role: UserRole,
) -> User:
    user_id = auth_adapter.seed_user(email=email, password=password)
    user = User(
        id=user_id,
        email=email.lower(),
        first_name="Test",
        last_name="User",
        student_number=None,
        role=role,
        department=None,
        created_at=datetime.now(timezone.utc),
    )
    db_session.add(user)
    db_session.commit()
    return user


def _token(auth_client: TestClient, email: str, password: str) -> str:
    response = auth_client.post(
        "/api/auth/signin",
        json={"email": email, "password": password},
    )
    assert response.status_code == 200
    return response.json()["access_token"]


@pytest.fixture()
def storage_root(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    root = tmp_path / "storage"
    root.mkdir()
    monkeypatch.setattr(settings, "file_storage_root", str(root))
    return root


def test_upload_unauthenticated(
    auth_client: TestClient,
    db_session: Session,
    storage_root: Path,
) -> None:
    response = auth_client.post(
        "/api/jobs/upload",
        files={"file": ("part.gcode", SAMPLE_GCODE, "application/octet-stream")},
    )
    assert response.status_code == 401
    _assert_safe_error_payload(response, storage_root=storage_root)
    _assert_no_jobs(db_session)
    _assert_no_files(storage_root)


def test_upload_gcode_success_as_student(
    auth_client: TestClient,
    db_session: Session,
    auth_adapter: FakeAuthAdapter,
    storage_root: Path,
) -> None:
    user = _seed_profile(
        db_session=db_session,
        auth_adapter=auth_adapter,
        email=STUDENT_EMAIL,
        password=STUDENT_PASSWORD,
        role=UserRole.STUDENT,
    )
    token = _token(auth_client, STUDENT_EMAIL, STUDENT_PASSWORD)

    response = auth_client.post(
        "/api/jobs/upload",
        headers={"Authorization": f"Bearer {token}"},
        files={"file": ("my-part.gcode", SAMPLE_GCODE, "application/octet-stream")},
    )
    assert response.status_code == 201
    data = response.json()
    assert data["status"] == "pending_selection"
    assert data["original_filename"] == "my-part.gcode"
    assert data["gcode_path"] == f"{user.id}/{data['id']}.gcode"
    assert not data["gcode_path"].startswith("/")
    assert str(storage_root) not in data["gcode_path"]
    assert ".." not in data["gcode_path"]

    disk_path = storage_root / data["gcode_path"]
    assert disk_path.is_file()
    assert disk_path.read_bytes() == SAMPLE_GCODE

    job = db_session.get(PrintJob, UUID(data["id"]))
    assert job is not None
    assert job.status == JobStatus.PENDING_SELECTION
    assert job.material_id is None
    assert job.printer_id is None
    assert job.user_id == user.id
    assert job.original_filename == "my-part.gcode"
    assert job.gcode_path == data["gcode_path"]


def test_upload_gco_success(
    auth_client: TestClient,
    db_session: Session,
    auth_adapter: FakeAuthAdapter,
    storage_root: Path,
) -> None:
    user = _seed_profile(
        db_session=db_session,
        auth_adapter=auth_adapter,
        email=STUDENT_EMAIL,
        password=STUDENT_PASSWORD,
        role=UserRole.STUDENT,
    )
    token = _token(auth_client, STUDENT_EMAIL, STUDENT_PASSWORD)

    response = auth_client.post(
        "/api/jobs/upload",
        headers={"Authorization": f"Bearer {token}"},
        files={"file": ("alias.gco", SAMPLE_GCODE, "application/octet-stream")},
    )
    assert response.status_code == 201
    data = response.json()
    assert data["original_filename"] == "alias.gco"
    assert data["gcode_path"] == f"{user.id}/{data['id']}.gco"
    assert (storage_root / data["gcode_path"]).is_file()


def test_upload_strips_client_path_components(
    auth_client: TestClient,
    db_session: Session,
    auth_adapter: FakeAuthAdapter,
    storage_root: Path,
) -> None:
    user = _seed_profile(
        db_session=db_session,
        auth_adapter=auth_adapter,
        email=STUDENT_EMAIL,
        password=STUDENT_PASSWORD,
        role=UserRole.STUDENT,
    )
    token = _token(auth_client, STUDENT_EMAIL, STUDENT_PASSWORD)

    response = auth_client.post(
        "/api/jobs/upload",
        headers={"Authorization": f"Bearer {token}"},
        files={
            "file": (
                "../../evil.gcode",
                SAMPLE_GCODE,
                "application/octet-stream",
            ),
        },
    )
    assert response.status_code == 201
    data = response.json()
    assert data["original_filename"] == "evil.gcode"
    assert data["gcode_path"] == f"{user.id}/{data['id']}.gcode"
    assert ".." not in data["gcode_path"]
    assert (storage_root / data["gcode_path"]).is_file()


@pytest.mark.parametrize(
    ("email", "password", "role"),
    [
        (FARMER_EMAIL, FARMER_PASSWORD, UserRole.FARMER),
        (ADMIN_EMAIL, ADMIN_PASSWORD, UserRole.ADMIN),
    ],
)
def test_upload_as_farmer_and_admin(
    auth_client: TestClient,
    db_session: Session,
    auth_adapter: FakeAuthAdapter,
    storage_root: Path,
    email: str,
    password: str,
    role: UserRole,
) -> None:
    del storage_root
    _seed_profile(
        db_session=db_session,
        auth_adapter=auth_adapter,
        email=email,
        password=password,
        role=role,
    )
    token = _token(auth_client, email, password)

    response = auth_client.post(
        "/api/jobs/upload",
        headers={"Authorization": f"Bearer {token}"},
        files={"file": ("role-check.gcode", SAMPLE_GCODE, "application/octet-stream")},
    )
    assert response.status_code == 201
    assert response.json()["status"] == "pending_selection"


def test_upload_wrong_extension_no_job_no_file(
    auth_client: TestClient,
    db_session: Session,
    auth_adapter: FakeAuthAdapter,
    storage_root: Path,
) -> None:
    _seed_profile(
        db_session=db_session,
        auth_adapter=auth_adapter,
        email=STUDENT_EMAIL,
        password=STUDENT_PASSWORD,
        role=UserRole.STUDENT,
    )
    token = _token(auth_client, STUDENT_EMAIL, STUDENT_PASSWORD)

    response = auth_client.post(
        "/api/jobs/upload",
        headers={"Authorization": f"Bearer {token}"},
        files={"file": ("notes.txt", b"hello", "text/plain")},
    )
    assert response.status_code == 400
    detail = response.json()["detail"]
    assert detail["code"] == "INVALID_EXTENSION"
    assert "gcode" in detail["message"].lower()
    _assert_safe_error_payload(response, storage_root=storage_root)
    _assert_no_jobs(db_session)
    _assert_no_files(storage_root)


def test_upload_empty_file_no_job_no_file(
    auth_client: TestClient,
    db_session: Session,
    auth_adapter: FakeAuthAdapter,
    storage_root: Path,
) -> None:
    _seed_profile(
        db_session=db_session,
        auth_adapter=auth_adapter,
        email=STUDENT_EMAIL,
        password=STUDENT_PASSWORD,
        role=UserRole.STUDENT,
    )
    token = _token(auth_client, STUDENT_EMAIL, STUDENT_PASSWORD)

    response = auth_client.post(
        "/api/jobs/upload",
        headers={"Authorization": f"Bearer {token}"},
        files={"file": ("empty.gcode", b"", "application/octet-stream")},
    )
    assert response.status_code == 400
    assert response.json()["detail"]["code"] == "EMPTY_FILE"
    _assert_safe_error_payload(response, storage_root=storage_root)
    _assert_no_jobs(db_session)
    _assert_no_files(storage_root)


def test_upload_oversize_no_job_no_file(
    auth_client: TestClient,
    db_session: Session,
    auth_adapter: FakeAuthAdapter,
    storage_root: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(settings, "max_upload_bytes", 16)
    _seed_profile(
        db_session=db_session,
        auth_adapter=auth_adapter,
        email=STUDENT_EMAIL,
        password=STUDENT_PASSWORD,
        role=UserRole.STUDENT,
    )
    token = _token(auth_client, STUDENT_EMAIL, STUDENT_PASSWORD)

    response = auth_client.post(
        "/api/jobs/upload",
        headers={"Authorization": f"Bearer {token}"},
        files={"file": ("big.gcode", b"x" * 64, "application/octet-stream")},
    )
    assert response.status_code == 400
    detail = response.json()["detail"]
    assert detail["code"] == "FILE_TOO_LARGE"
    assert "maximum upload size" in detail["message"].lower()
    _assert_safe_error_payload(response, storage_root=storage_root)
    _assert_no_jobs(db_session)
    _assert_no_files(storage_root)


def test_upload_write_failure_cleans_up_no_job(
    auth_client: TestClient,
    db_session: Session,
    auth_adapter: FakeAuthAdapter,
    storage_root: Path,
) -> None:
    _seed_profile(
        db_session=db_session,
        auth_adapter=auth_adapter,
        email=STUDENT_EMAIL,
        password=STUDENT_PASSWORD,
        role=UserRole.STUDENT,
    )
    token = _token(auth_client, STUDENT_EMAIL, STUDENT_PASSWORD)
    leaky = OSError(f"Permission denied: {storage_root.resolve()}/blocked.gcode")

    with patch(
        "app.services.storage_service.write_bytes",
        side_effect=leaky,
    ):
        response = auth_client.post(
            "/api/jobs/upload",
            headers={"Authorization": f"Bearer {token}"},
            files={"file": ("write-fail.gcode", SAMPLE_GCODE, "application/octet-stream")},
        )

    assert response.status_code == 500
    assert response.json()["detail"]["code"] == "UPLOAD_FAILED"
    assert response.json()["detail"]["message"] == "Upload could not be completed"
    _assert_safe_error_payload(response, storage_root=storage_root)
    _assert_no_jobs(db_session)
    _assert_no_files(storage_root)


def test_upload_db_failure_cleans_up_file(
    auth_client: TestClient,
    db_session: Session,
    auth_adapter: FakeAuthAdapter,
    storage_root: Path,
) -> None:
    _seed_profile(
        db_session=db_session,
        auth_adapter=auth_adapter,
        email=STUDENT_EMAIL,
        password=STUDENT_PASSWORD,
        role=UserRole.STUDENT,
    )
    token = _token(auth_client, STUDENT_EMAIL, STUDENT_PASSWORD)

    with patch.object(
        db_session,
        "commit",
        side_effect=RuntimeError(f"db down at {storage_root.resolve()}"),
    ):
        response = auth_client.post(
            "/api/jobs/upload",
            headers={"Authorization": f"Bearer {token}"},
            files={"file": ("fail.gcode", SAMPLE_GCODE, "application/octet-stream")},
        )

    assert response.status_code == 500
    assert response.json()["detail"]["code"] == "UPLOAD_FAILED"
    assert response.json()["detail"]["message"] == "Upload could not be completed"
    _assert_safe_error_payload(response, storage_root=storage_root)
    _assert_no_jobs(db_session)
    _assert_no_files(storage_root)
