; generated by PrusaSlicer test fixture

M862.1 P0.4 A0 F1
M862.3 P "COREONE"
M862.5 P2
M862.6 P"Input shaper"
G28
G1 X10 Y10 Z0.2 F3000
M104 S0
M140 S0
M107
M84 X Y E

; prusaslicer_config = begin
; printer_model = COREONE
; printer_variant = HF0.4
; printer_settings_id = Prusa CORE One HF0.4 nozzle
; printer_technology = FFF
; print_settings_id = 0.15mm SPEED @COREONE HF0.4
; nozzle_diameter = 0.4
; nozzle_high_flow = 1
; filament_abrasive = 0
; filament_colour = #FF8000
; filament_settings_id = Prusament PLA @COREONE HF0.4
; bed_shape = 0x0,250x0,250x220,0x220
; max_print_height = 270
; max_layer_z = 20
; temperature = 230
; bed_temperature = 60
; first_layer_temperature = 230
; first_layer_bed_temperature = 60
; layer_height = 0.15
; filament used [g] = 12.8
; estimated printing time (normal mode) = 1h 5m
; prusaslicer_config = end
