; generated by PrusaSlicer 2.9.0+synthetic on 2026-08-17 at 00:00:00 UTC
; synthetic test fixture for the confirmed COREONE HF0.4 hardware profile
M862.1 P0.4 A0 F1
M862.3 P "COREONE"
M862.6 P"Input shaper"
G90
G28
M104 S220
M140 S60
M141 S35
G1 X20 Y20 Z0.2 F3000
; prusaslicer_config = begin
; estimated printing time (normal mode) = 5m 0s
; filament used [mm] = 800
; filament used [cm3] = 1.93
; filament used [g] = 2.39
; printer_model = COREONE
; bed_shape = 0x0,250x0,250x220,0x220
; max_print_height = 270
; filament_type = PLA
; nozzle_diameter = 0.4
; nozzle_high_flow = 1
; printer_settings_id = Prusa CORE One HF0.4 nozzle
; temperature = 220
; bed_temperature = 60
; chamber_temperature = 35
; filament_density = 1.24
; prusaslicer_config = end
