; generated by PrusaSlicer 2.9.0+synthetic on 2026-08-17 at 00:00:00 UTC
; synthetic mismatch: CORE One G-code submitted to the XL worker
M862.1 P0.4 A0 F1
M862.3 P "COREONE"
M862.6 P"Input shaper"
G90
G28
G1 X10 Y10 Z0.2 F3000
; prusaslicer_config = begin
; estimated printing time (normal mode) = 10m
; filament used [g] = 3.58
; printer_model = COREONE
; bed_shape = 0x0,250x0,250x220,0x220
; max_print_height = 270
; filament_type = PLA
; nozzle_diameter = 0.4
; nozzle_high_flow = 1
; printer_settings_id = Prusa CORE One HF0.4 nozzle
; temperature = 215
; bed_temperature = 60
; prusaslicer_config = end
