; generated by PrusaSlicer 2.9.0+synthetic on 2026-08-17 at 00:00:00 UTC
; synthetic test fixture for the confirmed XL5IS hardware profile
M862.1 T0 P0.4 A0 F0
M862.3 P "XL"
M862.6 P"Input shaper"
T0
G90
G28
M104 S215
M140 S60
G1 X10 Y10 Z0.2 F3000
; prusaslicer_config = begin
; estimated printing time (normal mode) = 10m 0s
; filament used [mm] = 1200,0,0,0,0
; filament used [cm3] = 2.89,0,0,0,0
; filament used [g] = 3.58,0,0,0,0
; printer_model = XL5IS
; bed_shape = 0x0,360x0,360x360,0x360
; max_print_height = 360
; filament_type = PLA,PLA,PLA,PLA,PLA
; nozzle_diameter = 0.4,0.4,0.4,0.4,0.4
; nozzle_high_flow = 0,0,0,0,0
; printer_settings_id = Original Prusa XL - 5T Input Shaper 0.4 nozzle
; temperature = 215,215,215,215,215
; bed_temperature = 60
; filament_density = 1.24,1.24,1.24,1.24,1.24
; prusaslicer_config = end
